spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      show-sql: true
      open-in-view: true
    properties:
      hibernate: null
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://demcruzsystem.cldyuyxqjeig.sa-east-1.rds.amazonaws.com/sys?useTimezone=true&serverTimezone=UTC
    username: admin
    password: mysqlaws
